-- ============================================================
-- ONLINE COMPLAINT MANAGEMENT PORTAL
-- PostgreSQL / Neon Database Schema
-- File: database/schema.sql
-- ============================================================

BEGIN;

-- ============================================================
-- 1. DEPARTMENTS
-- ============================================================

CREATE TABLE IF NOT EXISTS departments
(
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(120) NOT NULL UNIQUE,

    description TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 2. USERS
-- ============================================================

CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name VARCHAR(150) NOT NULL,

    email VARCHAR(180) NOT NULL UNIQUE,

    mobile VARCHAR(20),

    username VARCHAR(100) UNIQUE,

    address TEXT,

    password_hash VARCHAR(255) NOT NULL,

    role VARCHAR(20) NOT NULL DEFAULT 'user'
        CHECK (
            role IN (
                'user',
                'staff',
                'admin'
            )
        ),

    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (
            status IN (
                'active',
                'inactive'
            )
        ),

    department_id BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_department
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


-- Case-insensitive email uniqueness
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower
ON users (LOWER(email));


CREATE INDEX IF NOT EXISTS idx_users_role
ON users(role);


CREATE INDEX IF NOT EXISTS idx_users_status
ON users(status);


CREATE INDEX IF NOT EXISTS idx_users_department
ON users(department_id);


-- ============================================================
-- 3. CATEGORIES
-- ============================================================

CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(120) NOT NULL UNIQUE,

    description TEXT,

    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (
            status IN (
                'active',
                'inactive'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX IF NOT EXISTS idx_categories_status
ON categories(status);


-- ============================================================
-- 4. COMPLAINTS
-- ============================================================

CREATE TABLE IF NOT EXISTS complaints
(
    complaint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    complaint_code VARCHAR(30) UNIQUE,

    user_id BIGINT NOT NULL,

    category_id BIGINT NOT NULL,

    department_id BIGINT,

    assigned_staff_id BIGINT,

    title VARCHAR(200) NOT NULL,

    description TEXT NOT NULL,

    priority VARCHAR(20) NOT NULL DEFAULT 'medium'
        CHECK (
            priority IN (
                'low',
                'medium',
                'high',
                'urgent'
            )
        ),

    status VARCHAR(30) NOT NULL DEFAULT 'pending'
        CHECK (
            status IN (
                'pending',
                'assigned',
                'in_progress',
                'resolved',
                'closed',
                'rejected'
            )
        ),

    location VARCHAR(255),

    address TEXT,

    pincode VARCHAR(10),

    /*
     * For the current college-project implementation,
     * complaintController.js can store an uploaded image
     * as a Base64 data URL here.
     */
    image_url TEXT,

    resolution TEXT,

    due_date TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_complaint_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_complaint_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_complaint_department
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_complaint_staff
        FOREIGN KEY (assigned_staff_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


CREATE INDEX IF NOT EXISTS idx_complaints_user
ON complaints(user_id);


CREATE INDEX IF NOT EXISTS idx_complaints_category
ON complaints(category_id);


CREATE INDEX IF NOT EXISTS idx_complaints_department
ON complaints(department_id);


CREATE INDEX IF NOT EXISTS idx_complaints_staff
ON complaints(assigned_staff_id);


CREATE INDEX IF NOT EXISTS idx_complaints_status
ON complaints(status);


CREATE INDEX IF NOT EXISTS idx_complaints_priority
ON complaints(priority);


CREATE INDEX IF NOT EXISTS idx_complaints_created_at
ON complaints(created_at DESC);


CREATE INDEX IF NOT EXISTS idx_complaints_status_created
ON complaints(status, created_at DESC);


-- ============================================================
-- 5. COMPLAINT STATUS HISTORY
-- ============================================================

CREATE TABLE IF NOT EXISTS complaint_status_history
(
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    complaint_id BIGINT NOT NULL,

    status VARCHAR(30) NOT NULL
        CHECK (
            status IN (
                'pending',
                'assigned',
                'in_progress',
                'resolved',
                'closed',
                'rejected'
            )
        ),

    remarks TEXT,

    updated_by BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_history_complaint
        FOREIGN KEY (complaint_id)
        REFERENCES complaints(complaint_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_history_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


CREATE INDEX IF NOT EXISTS idx_history_complaint
ON complaint_status_history(complaint_id);


CREATE INDEX IF NOT EXISTS idx_history_created_at
ON complaint_status_history(created_at);


-- ============================================================
-- 6. FEEDBACK
-- ============================================================

CREATE TABLE IF NOT EXISTS feedback
(
    feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    complaint_id BIGINT,

    rating INTEGER NOT NULL
        CHECK (
            rating >= 1
            AND rating <= 5
        ),

    feedback_type VARCHAR(50) NOT NULL DEFAULT 'complaint_resolution'
        CHECK (
            feedback_type IN (
                'complaint_resolution',
                'staff_service',
                'portal_experience',
                'other'
            )
        ),

    comments TEXT NOT NULL,

    recommend VARCHAR(10) NOT NULL DEFAULT 'yes'
        CHECK (
            recommend IN (
                'yes',
                'no'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_feedback_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_feedback_complaint
        FOREIGN KEY (complaint_id)
        REFERENCES complaints(complaint_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_feedback_complaint_user
        UNIQUE (complaint_id, user_id)
);


CREATE INDEX IF NOT EXISTS idx_feedback_user
ON feedback(user_id);


CREATE INDEX IF NOT EXISTS idx_feedback_complaint
ON feedback(complaint_id);


CREATE INDEX IF NOT EXISTS idx_feedback_rating
ON feedback(rating);


-- ============================================================
-- 7. CONTACT MESSAGES
-- ============================================================

CREATE TABLE IF NOT EXISTS contact_messages
(
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(150) NOT NULL,

    email VARCHAR(180) NOT NULL,

    subject VARCHAR(250) NOT NULL,

    message TEXT NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'unread'
        CHECK (
            status IN (
                'unread',
                'read',
                'archived'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX IF NOT EXISTS idx_contact_messages_status
ON contact_messages(status);


CREATE INDEX IF NOT EXISTS idx_contact_messages_created
ON contact_messages(created_at DESC);


-- ============================================================
-- AUTOMATIC updated_at FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
AS $$
BEGIN

    NEW.updated_at = CURRENT_TIMESTAMP;

    RETURN NEW;

END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- USERS UPDATED_AT TRIGGER
-- ============================================================

DROP TRIGGER IF EXISTS trg_users_updated_at
ON users;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- DEPARTMENTS UPDATED_AT TRIGGER
-- ============================================================

DROP TRIGGER IF EXISTS trg_departments_updated_at
ON departments;

CREATE TRIGGER trg_departments_updated_at
BEFORE UPDATE ON departments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- CATEGORIES UPDATED_AT TRIGGER
-- ============================================================

DROP TRIGGER IF EXISTS trg_categories_updated_at
ON categories;

CREATE TRIGGER trg_categories_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- COMPLAINTS UPDATED_AT TRIGGER
-- ============================================================

DROP TRIGGER IF EXISTS trg_complaints_updated_at
ON complaints;

CREATE TRIGGER trg_complaints_updated_at
BEFORE UPDATE ON complaints
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


COMMIT;